---
title: "Reproducible document"
author: "Julian Bjerrekaer"
format: html
---

## Basics of R

```{r}
1 + 1
```

## About me

- Julian Bjerrekær
- Steno Diabetes Center
- University of Copenhagen

I am an **old** man. I live in *Copenhagen*.

```{r}
3 * 3
```
## Testing for Git

The weather was sunny today.

## Setup code chunk

```{r setup}
#| message: false
#| warning: false
library(tidyverse)
post_meal_data <- read_csv2(
  here::here("data/post-meal-insulin.csv")
)
```

## Showing the data

```{r}
post_meal_data
```

```{r}
glimpse(post_meal_data)
```

```{r}
ggplot(post_meal_data, aes(x = BMI)) +
geom_histogram()
```

```{r}
#| fig-cap: "Distribution of BMI"
#| label: fig-bmi-histo
#| message: false
ggplot(post_meal_data, aes(x = BMI)) +
geom_histogram()
```

@fig-bmi-histo

## Exercise: discrete plots.

```{r}
#| fig-cap: "Distribution of glycemia"
#| label: fig-glykemi-bar
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```

See @fig-glykemi-bar above for a cool plot!






